# Generated by Django 2.2 on 2019-04-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsworldonline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='name',
            new_name='email',
        ),
    ]
